//
//  IngredientController.swift
//  Drinx
//
//  Created by Jeremiah Hawks on 4/13/17.
//  Copyright © 2017 Jeremiah Hawks. All rights reserved.
//

import Foundation


class IngredientController {
    
    let ingredientStrings = ["Light rum" , "Applejack" , "Gin" , "Dark rum" , "Sweet Vermouth" , "Strawberry schnapps" , "Scotch" , "Apricot brandy" , "Triple sec" , "Southern Comfort" , "Orange bitters" , "Brandy" , "Lemon vodka" , "Blended whiskey" , "Dry Vermouth" , "Amaretto" , "Tea" , "Creme de Cacao" , "Apple brandy" , "Dubonnet Blanc" , "Apple schnapps" , "Añejo rum" , "Champagne" , "Coffee liqueur" , "Rum" , "Cachaca" , "Sugar" , "Blackberry brandy" , "Calvados" , "Ice" , "Lemon" , "Coffee brandy" , "Bourbon" , "Irish whiskey" , "Vodka" , "Tequila" , "Bitters" , "Lime juice" , "Egg" , "Mint" , "Sherry" , "Cherry brandy" , "Canadian whisky" , "Kahlua" , "Yellow Chartreuse" , "Cognac" , "demerara Sugar" , "Sake" , "Dubonnet Rouge" , "Anis" , "White Creme de Menthe" , "Gold tequila" , "Sweet and sour" , "Salt" , "Galliano" , "Green Creme de Menthe" , "Kummel" , "Anisette" , "Carbonated water" , "Lemon peel" , "White wine" , "Sloe gin" , "Melon liqueur" , "Swedish Punsch" , "Peach brandy" , "Passion fruit juice" , "Peppermint schnapps" , "Creme de Noyaux" , "Grenadine" , "Port" , "Red wine" , "Rye whiskey" , "Grapefruit juice" , "Ricard" , "Banana liqueur" , "Vanilla ice-cream" , "Whiskey" , "Creme de Banane" , "Lime juice cordial" , "Strawberry liqueur" , "Sambuca" , "Peach schnapps" , "Apple juice" , "Berries" , "Blueberries" , "Orange juice" , "Pineapple juice" , "Cranberries" , "Brown sugar" , "Milk" , "Egg yolk" , "Lemon juice" , "Soda water" , "Coconut liqueur" , "Cream" , "Pineapple" , "Sugar syrup" , "Ginger ale" , "Worcestershire sauce" , "Ginger" , "Strawberries" , "Chocolate syrup" , "Yoghurt" , "Grape juice" , "Orange" , "Apple cider" , "Banana" , "Mango" , "Soy milk" , "Lime" , "Cantaloupe" , "Grapes" , "Kiwi" , "Tomato juice" , "Cocoa powder" , "Chocolate" , "Heavy cream" , "Peach Vodka" , "Ouzo" , "Coffee" , "Spiced rum" , "Water" , "Espresso" , "Angelica root" , "Condensed milk" , "Honey" , "Whipping cream" , "Half-and-half" , "Bread" , "Plums" , "Johnnie Walker" , "Vanilla" , "Apple" , "Orange rum" , "Everclear" , "Kool-Aid" , "Lemonade" , "Cranberry juice" , "Eggnog" , "Carbonated soft drink" , "Cloves" , "Raisins" , "Almond" , "Beer" , "Pink lemonade" , "Sherbet" , "Peach nectar" , "Firewater" , "Absolut Citron" , "Malibu rum" , "Midori melon liqueur" , "151 proof rum" , "Bacardi Limon" , "Bailey's irish cream" , "Lager" , "Orange vodka" , "Blue Curacao" , "Absolut Vodka" , "Jägermeister" , "Jack Daniels" , "Drambuie" , "Whisky" , "White rum" , "Pisco" , "Irish cream" , "Yukon Jack" , "Goldschlager" , "Butterscotch schnapps" , "Grand Marnier" , "Peachtree schnapps" , "Absolut Kurant" , "Ale" , "Chambord raspberry liqueur" , "Tia maria" , "Chocolate liqueur" , "Frangelico" , "Barenjager" , "Hpnotiq" , "Coca-Cola" , "Tuaca" , "Tang" , "Tropicana" , "Grain alcohol" , "Schnapps" , "Cider" , "Aftershock" , "Sprite" , "Rumple Minze" , "Key Largo schnapps" , "Pisang Ambon" , "Pernod" , "7-Up" , "Limeade" , "Gold rum" , "Wild Turkey" , "Cointreau" , "Lime vodka" , "Maraschino cherry juice" , "Creme de Cassis" , "Zima" , "Crown Royal" , "Cardamom" , "Orange Curacao" , "Tabasco sauce" , "Peach liqueur" , "Curacao" , "Cherry Heering" , "Fruit punch" , "Vermouth" , "Cherry juice" , "Cinnamon schnapps" , "Orange peel" , "Advocaat" , "Clamato juice" , "Sour mix" , "Apfelkorn" , "Green Chartreuse" , "Root beer schnapps" , "Coconut rum" , "Raspberry schnapps" , "Black Sambuca" , "Vanilla vodka" , "Root beer" , "Absolut Peppar" , "Vanilla schnapps" , "Orange liqueur" , "Kiwi liqueur" , "Hot chocolate" , "Jello" , "Mountain Dew" , "Blueberry schnapps" , "Maui" , "Tennessee whiskey" , "White chocolate liqueur" , "Cream of coconut" , "Citrus vodka" , "Fruit juice" , "Cranberry vodka" , "Campari" , "Corona" , "Chocolate ice-cream" , "Jim Beam" , "Aquavit" , "Hawaiian Punch" , "Blackberry schnapps" , "Chocolate milk" , "Watermelon schnapps" , "Beef bouillon" , "Dr. Pepper" , "Iced tea" , "Hot Damn" , "Club soda" , "Benedictine" , "Dark Creme de Cacao" , "Black rum" , "Cherry Cola" , "Absinthe" , "Angostura bitters" , "Tequila Rose" , "Guinness stout" , "Orange soda" , "Wildberry schnapps" , "Lemon-lime soda" , "Godiva liqueur" , "Baileys irish cream" , "Schweppes Russchian" , "Melon vodka" , "Sour Apple Pucker" , "Raspberry vodka" , "coconut milk"]


    static let share = IngredientController()
    
    var ingredients = CabinetController.shared.myCabinet.myIngredients
    
    var myCabinetIngredientStrings: [String] {
        var strings: [String] = []
        for ingredient in ingredients {
            strings.append(ingredient.name)
        }
        return strings
    }
    
    func add(item: String){
        let ingredient =  Ingredient(name: item)
            ingredients.append(ingredient)
    
    }
    
    func delete(ingredient: Ingredient) {
        for (index, ingredientObj) in ingredients.enumerated() {
            if ingredient.name == ingredientObj.name {
                ingredients.remove(at: index)
            }
        }
        for (index, ingredientObj) in CabinetController.shared.myCabinet.myIngredients.enumerated() {
            if ingredient.name == ingredientObj.name {
                CabinetController.shared.myCabinet.myIngredients.remove(at: index)
            }
        }
    }
    
    let ingredientDictionary = ["151 proof rum": ["151 proof rum"],
                                "7-Up": ["7-Up"],
                                "Absinthe": ["Absinthe"],
                                "Absolut Citron": ["Absolut Citron"],
                                "Absolut Kurant": ["Absolut Kurant"],
                                "Absolut Peppar": ["Absolut Peppar"],
                                "Absolut Vodka": ["Absolut Vodka"],
                                "Advocaat": ["Advocaat"],
                                "Aftershock": ["Aftershock"],
                                "Agave Syrup": ["Agave Syrup"],
                                "Ale": ["Ale"],
                                "Allspice": ["Allspice"],
                                "Almond": ["Almond"],
                                "Almond flavoring": ["Almond flavoring"],
                                "Almond liqueur": ["Amaretto"],
                                "Amaretto": ["Amaretto"],
                                "Angelica root": ["Angelica root"],
                                "Angostura bitters": ["Angostura bitters"],
                                "Angostura Bitters": ["Angostura Bitters"],
                                "Anis": ["Anis"],
                                "Anise": ["Anise"],
                                "Anisette": ["Anisette"],
                                "Añejo rum": ["Añejo rum"],
                                "Aperol": ["Aperol"],
                                "Apfelkorn": ["Apfelkorn"],
                                "Apple": ["Apple"],
                                "Apple brandy": ["Apple brandy"],
                                "Apple cider": ["Apple cider"],
                                "Apple juice": ["Apple juice"],
                                "Apple schnapps": ["Apple schnapps"],
                                "Applejack": ["Applejack"],
                                "Apricot": ["Apricot"],
                                "Apricot brandy": ["Apricot brandy"],
                                "Apricot nectar": ["Apricot nectar"],
                                "Aquavit": ["Aquavit"],
                                "Asafoetida": ["Asafoetida"],
                                "Bacardi": ["151 proof rum", "Rum"],
                                "Bacardi 151": ["151 proof rum"],
                                "Bacardi Limon": ["Bacardi Limon"],
                                "Bailey's irish cream": ["Bailey\'s irish cream"],
                                "Baileys irish cream": ["Baileys irish cream"],
                                "Banana": ["Banana"],
                                "Banana liqueur": ["Banana liqueur"],
                                "Banana rum": ["Banana rum"],
                                "Banana syrup": ["Banana syrup"],
                                "Barenjager": ["Barenjager"],
                                "Beef bouillon": ["Beef bouillon"],
                                "Beer": ["Beer"],
                                "Benedictine": ["Benedictine"],
                                "Berries": ["Berries"],
                                "Bitter lemon": ["Bitter lemon"],
                                "Bitters": ["Bitters"],
                                "Black pepper": ["Black pepper"],
                                "Black rum": ["Black rum"],
                                "Black Sambuca": ["Black Sambuca"],
                                "Blackberries": ["Blackberries"],
                                "Blackberry brandy": ["Blackberry brandy"],
                                "Blackberry schnapps": ["Blackberry schnapps"],
                                "Blackcurrant cordial": ["Blackcurrant cordial"],
                                "Blackcurrant schnapps": ["Blackcurrant schnapps"],
                                "Blackcurrant squash": ["Blackcurrant squash"],
                                "Blended whiskey": ["Blended whiskey"],
                                "Blue Curacao": ["Blue Curacao"],
                                "Blueberries": ["Blueberries"],
                                "Blueberry schnapps": ["Blueberry schnapps"],
                                "Bourbon": ["Bourbon"],
                                "Brandy": ["Brandy"],
                                "Bread": ["Bread"],
                                "Brown sugar": ["Brown sugar"],
                                "Butter": ["Butter"],
                                "Butterscotch schnapps": ["Butterscotch schnapps"],
                                "Cachaca": ["Cachaca"],
                                "Calvados": ["Calvados"],
                                "Campari": ["Campari"],
                                "Canadian whisky": ["Canadian whisky"],
                                "Candy": ["Candy"],
                                "Cantaloupe": ["Cantaloupe"],
                                "Caramel coloring": ["Caramel coloring"],
                                "Carbonated soft drink": ["Carbonated soft drink"],
                                "Carbonated water": ["Carbonated water"],
                                "Cardamom": ["Cardamom"],
                                "Carrot": ["Carrot"],
                                "Cayenne pepper": ["Cayenne pepper"],
                                "Celery": ["Celery"],
                                "Celery salt": ["Celery salt"],
                                "Chambord raspberry liqueur": ["Chambord raspberry liqueur"],
                                "Champagne": ["Champagne"],
                                "Cherries": ["Cherries"],
                                "Cherry": ["Cherry"],
                                "Cherry brandy": ["Cherry brandy"],
                                "Cherry Cola": ["Cherry Cola"],
                                "Cherry Grenadine": ["Cherry Grenadine"],
                                "Cherry Heering": ["Cherry Heering"],
                                "Cherry juice": ["Cherry juice"],
                                "Cherry liqueur": ["Cherry liqueur"],
                                "Chocolate": ["Chocolate"],
                                "Chocolate ice-cream": ["Chocolate ice-cream"],
                                "Chocolate liqueur": ["Chocolate liqueur"],
                                "Chocolate milk": ["Chocolate milk"],
                                "Chocolate syrup": ["Chocolate syrup"],
                                "Cider": ["Cider"],
                                "Cinnamon": ["Cinnamon"],
                                "Cinnamon schnapps": ["Cinnamon schnapps"],
                                "Citrus vodka": ["Citrus vodka"],
                                "Clamato juice": ["Clamato juice"],
                                "Clove": ["Clove"],
                                "Cloves": ["Cloves"],
                                "Club soda": ["Soda water", "Club soda"],
                                "Coca-Cola": ["Coca-Cola"],
                                "Cocktail onion": ["Cocktail onion"],
                                "Cocoa powder": ["Cocoa powder"],
                                "Coconut cream": ["Coconut cream"],
                                "Coconut liqueur": ["Coconut liqueur"],
                                "Coconut milk": ["Coconut milk"],
                                "coconut milk": ["coconut milk"],
                                "Coconut rum": ["Coconut rum"],
                                "Coconut syrup": ["Coconut syrup"],
                                "Coffee": ["Coffee"],
                                "Coffee brandy": ["Coffee brandy"],
                                "Coffee liqueur": ["Coffee liqueur", "Kahlua"],
                                "Cognac": ["Cognac"],
                                "Cointreau": ["Cointreau"],
                                "Coke": ["Coca-Cola", "Pepsi Cola"],
                                "Cola": ["Coca-Cola", "Pepsi Cola"],
                                "Collins mix": ["Collins mix"],
                                "Condensed milk": ["Condensed milk"],
                                "Coriander": ["Coriander"],
                                "Corn syrup": ["Corn syrup"],
                                "Cornstarch": ["Cornstarch"],
                                "Corona": ["Corona"],
                                "Cranberries": ["Cranberries"],
                                "Cranberry juice": ["Cranberry juice"],
                                "Cranberry liqueur": ["Cranberry liqueur"],
                                "Cranberry vodka": ["Cranberry vodka"],
                                "Cream": ["Cream"],
                                "Cream of coconut": ["Cream of coconut"],
                                "Cream soda": ["Cream soda"],
                                "Creme de Almond": ["Creme de Almond"],
                                "Creme de Banane": ["Creme de Banane"],
                                "Creme de Cacao": ["Creme de Cacao"],
                                "Creme de Cassis": ["Creme de Cassis"],
                                "Creme de Noyaux": ["Creme de Noyaux"],
                                "Crown Royal": ["Crown Royal"],
                                "Crystal light": ["Crystal light"],
                                "Cucumber": ["Cucumber"],
                                "Cumin seed": ["Cumin seed"],
                                "Curacao": ["Curacao"],
                                "Cynar": ["Cynar"],
                                "Daiquiri mix": ["Daiquiri mix"],
                                "Dark Creme de Cacao": ["Dark Creme de Cacao"],
                                "Dark rum": ["Dark rum"],
                                "demerara Sugar": ["demerara Sugar"],
                                "Disaronno": ["Amaretto"],
                                "Dr. Pepper": ["Dr. Pepper"],
                                "Drambuie": ["Drambuie"],
                                "Dry Vermouth": ["Dry Vermouth"],
                                "Dubonnet Blanc": ["Dubonnet Blanc"],
                                "Dubonnet Rouge": ["Dubonnet Rouge"],
                                "Egg": ["Egg"],
                                "Egg white": ["Egg white"],
                                "Egg yolk": ["Egg yolk"],
                                "Eggnog": ["Eggnog"],
                                "Erin Cream": ["Erin Cream"],
                                "Espresso": ["Espresso"],
                                "Everclear": ["Everclear"],
                                "Fanta": ["Fanta"],
                                "Fennel seeds": ["Fennel seeds"],
                                "Figs": ["Figs"],
                                "Firewater": ["Firewater"],
                                "Food coloring": ["Food coloring"],
                                "Forbidden Fruit": ["Forbidden Fruit"],
                                "Frangelico": ["Frangelico"],
                                "Fresca": ["Fresca"],
                                "Fruit": ["Fruit"],
                                "Fruit juice": ["Fruit juice"],
                                "Fruit punch": ["Fruit punch"],
                                "Galliano": ["Galliano"],
                                "Gatorade": ["Gatorade"],
                                "Gin": ["Gin"],
                                "Ginger": ["Ginger"],
                                "Ginger ale": ["Ginger ale"],
                                "Ginger beer": ["Ginger beer"],
                                "Glycerine": ["Glycerine"],
                                "Godiva liqueur": ["Godiva liqueur"],
                                "Gold rum": ["Gold rum"],
                                "Gold tequila": ["Gold tequila"],
                                "Goldschlager": ["Goldschlager"],
                                "Grain alcohol": ["Grain alcohol"],
                                "Grand Marnier": ["Grand Marnier"],
                                "Grape juice": ["Grape juice"],
                                "Grape soda": ["Grape soda"],
                                "Grapefruit": ["Grapefruit"],
                                "Grapefruit juice": ["Grapefruit juice"],
                                "Grapefruit schnapps": ["Grapefruit schnapps"],
                                "Grapes": ["Grapes"],
                                "Green Chartreuse": ["Green Chartreuse"],
                                "Green Creme de Menthe": ["Green Creme de Menthe"],
                                "Grenadine": ["Grenadine"],
                                "Guava juice": ["Guava juice"],
                                "Guinness stout": ["Guinness stout"],
                                "Half-and-half": ["Half-and-half"],
                                "Hawaiian Punch": ["Hawaiian Punch"],
                                "Hazelnut liqueur": ["Hazelnut liqueur"],
                                "Heavy cream": ["Heavy cream"],
                                "Honey": ["Honey"],
                                "honey": ["honey"],
                                "Hoopers Hooch": ["Hoopers Hooch"],
                                "Horseradish": ["Horseradish"],
                                "Hot chocolate": ["Hot chocolate"],
                                "Hot Damn": ["Hot Damn"],
                                "Hot red pepper flakes": ["Hot red pepper flakes"],
                                "Hpnotiq": ["Hpnotiq"],
                                "Ice": ["Ice"],
                                "Ice-cream": ["Ice-cream"],
                                "Iced tea": ["Iced tea"],
                                "Irish cream": ["Irish cream"],
                                "Irish whiskey": ["Irish whiskey"],
                                "Jack Daniels": ["Jack Daniels"],
                                "Jägermeister": ["Jägermeister"],
                                "Jello": ["Jello"],
                                "Jim Beam": ["Jim Beam"],
                                "Johnnie Walker": ["Johnnie Walker"],
                                "Kahlua": ["Kahlua", "Coffee liqueur"],
                                "Key Largo schnapps": ["Key Largo schnapps"],
                                "Kirschwasser": ["Kirschwasser"],
                                "Kiwi": ["Kiwi"],
                                "Kiwi liqueur": ["Kiwi liqueur"],
                                "Kool-Aid": ["Kool-Aid"],
                                "Kummel": ["Kummel"],
                                "Lager": ["Lager"],
                                "Lavender": ["Lavender"],
                                "Lemon": ["Lemon"],
                                "Lemon juice": ["Lemon juice"],
                                "lemon juice": ["lemon juice"],
                                "Lemon Juice": ["Lemon Juice"],
                                "Lemon peel": ["Lemon peel"],
                                "Lemon soda": ["Lemon soda"],
                                "Lemon vodka": ["Lemon vodka"],
                                "Lemon-lime mix": ["Lemon-lime mix"],
                                "Lemon-lime soda": ["Lemon-lime soda"],
                                "Lemonade": ["Lemonade"],
                                "Licorice root": ["Licorice root"],
                                "Light cream": ["Light cream"],
                                "Light rum": ["Light rum"],
                                "Lillet": ["Lillet"],
                                "Lime": ["Lime"],
                                "lime juice": ["lime juice"],
                                "Lime Juice": ["Lime Juice"],
                                "Lime juice": ["Lime juice"],
                                "Lime juice cordial": ["Lime juice cordial"],
                                "Lime liqueur": ["Lime liqueur"],
                                "Lime peel": ["Lime peel"],
                                "Lime vodka": ["Lime vodka"],
                                "Limeade": ["Limeade"],
                                "Madeira": ["Madeira"],
                                "Malibu rum": ["Malibu rum"],
                                "Mandarin": ["Mandarin"],
                                "Mandarine Napoleon": ["Mandarine Napoleon"],
                                "Mango": ["Mango"],
                                "Maple syrup": ["Maple syrup"],
                                "Maraschino cherry": ["Maraschino cherry"],
                                "Maraschino cherry juice": ["Maraschino cherry juice"],
                                "Maraschino liqueur": ["Maraschino liqueur"],
                                "maraschino liqueur": ["maraschino liqueur"],
                                "Margarita mix": ["Margarita mix"],
                                "Marjoram leaves": ["Marjoram leaves"],
                                "Marshmallows": ["Marshmallows"],
                                "Maui": ["Maui"],
                                "Melon liqueur": ["Melon liqueur"],
                                "Melon vodka": ["Melon vodka"],
                                "Mezcal": ["Mezcal"],
                                "Midori melon liqueur": ["Midori melon liqueur"],
                                "Milk": ["Milk"],
                                "Mint": ["Mint"],
                                "Mint syrup": ["Mint syrup"],
                                "Monin bitter": ["Monin bitter"],
                                "Mountain Dew": ["Mountain Dew"],
                                "Nutmeg": ["Nutmeg"],
                                "Nuts": ["Nuts"],
                                "Olive": ["Olive"],
                                "Olive Brine": ["Olive Brine"],
                                "Orange": ["Orange"],
                                "Orange bitters": ["Orange bitters"],
                                "Orange Curacao": ["Orange Curacao"],
                                "Orange juice": ["Orange juice"],
                                "Orange liqueur": ["Orange liqueur"],
                                "Orange peel": ["Orange peel"],
                                "Orange rum": ["Orange rum"],
                                "Orange soda": ["Orange soda"],
                                "Orange spiral": ["Orange spiral"],
                                "Orange vodka": ["Orange vodka"],
                                "Oreo cookie": ["Oreo cookie"],
                                "Orgeat syrup": ["Orgeat syrup"],
                                "Ouzo": ["Ouzo"],
                                "Papaya": ["Papaya"],
                                "Papaya juice": ["Papaya juice"],
                                "Passion fruit juice": ["Passion fruit juice"],
                                "Passion fruit syrup": ["Passion fruit syrup"],
                                "Passoa": ["Passoa"],
                                "Peach": ["Peach"],
                                "Peach brandy": ["Peach brandy"],
                                "Peach juice": ["Peach juice"],
                                "Peach liqueur": ["Peach liqueur"],
                                "Peach nectar": ["Peach nectar"],
                                "Peach schnapps": ["Peach schnapps"],
                                "Peach Vodka": ["Peach Vodka"],
                                "Peachtree schnapps": ["Peachtree schnapps"],
                                "Pepper": ["Pepper"],
                                "Peppermint extract": ["Peppermint extract"],
                                "Peppermint schnapps": ["Peppermint schnapps"],
                                "Pepsi Cola": ["Coca-Cola", "Pepsi Cola"],
                                "Pernod": ["Pernod"],
                                "Peychaud bitters": ["Peychaud bitters"],
                                "Pina colada mix": ["Pina colada mix"],
                                "Pineapple": ["Pineapple"],
                                "Pineapple juice": ["Pineapple juice"],
                                "Pineapple rum": ["Pineapple rum"],
                                "Pineapple Syrup": ["Pineapple Syrup"],
                                "Pineapple vodka": ["Pineapple vodka"],
                                "Pineapple-orange juice": ["Pineapple-orange juice"],
                                "Pineapple-orange-banana juice": ["Pineapple-orange-banana juice"],
                                "Pink lemonade": ["Pink lemonade"],
                                "Pisang Ambon": ["Pisang Ambon"],
                                "Pisco": ["Pisco"],
                                "Plums": ["Plums"],
                                "Port": ["Port"],
                                "Powdered sugar": ["Powdered sugar"],
                                "Purple passion": ["Purple passion"],
                                "Raisins": ["Raisins"],
                                "Raspberry cordial": ["Raspberry cordial"],
                                "Raspberry jam": ["Raspberry jam"],
                                "Raspberry juice": ["Raspberry juice"],
                                "Raspberry liqueur": ["Raspberry liqueur"],
                                "Raspberry schnapps": ["Raspberry schnapps"],
                                "Raspberry syrup": ["Raspberry syrup"],
                                "Raspberry vodka": ["Raspberry vodka"],
                                "Razzmatazz": ["Razzmatazz"],
                                "Red wine": ["Red wine"],
                                "Ricard": ["Ricard"],
                                "Root beer": ["Root beer"],
                                "Root beer schnapps": ["Root beer schnapps"],
                                "Rum": ["Rum"],
                                "Rumple Minze": ["Rumple Minze"],
                                "Rye whiskey": ["Rye whiskey"],
                                "Sake": ["Sake"],
                                "Salt": ["Salt"],
                                "salt": ["salt"],
                                "Sambuca": ["Sambuca"],
                                "Sarsaparilla": ["Sarsaparilla"],
                                "Schnapps": ["Schnapps"],
                                "Schweppes Lemon": ["Schweppes Lemon"],
                                "Schweppes Russchian": ["Schweppes Russchian"],
                                "Scotch": ["Scotch"],
                                "Sherbet": ["Sherbet"],
                                "Sherry": ["Sherry"],
                                "Sirup of roses": ["Sirup of roses"],
                                "Sloe gin": ["Sloe gin"],
                                "Soda water": ["Club soda", "Soda water"],
                                "Sour Apple Pucker": ["Sour Apple Pucker"],
                                "Sour mix": ["Sour mix"],
                                "Southern Comfort": ["Southern Comfort"],
                                "Soy milk": ["Soy milk"],
                                "Soy sauce": ["Soy sauce"],
                                "Spiced rum": ["Spiced rum"],
                                "Sprite": ["Sprite"],
                                "squeezed orange": ["squeezed orange"],
                                "Squirt": ["Squirt"],
                                "St. Germain": ["St. Germain"],
                                "Stout": ["Stout"],
                                "Strawberries": ["Strawberries"],
                                "Strawberry juice": ["Strawberry juice"],
                                "Strawberry liqueur": ["Strawberry liqueur"],
                                "Strawberry schnapps": ["Strawberry schnapps"],
                                "Strawberry syrup": ["Strawberry syrup"],
                                "Sugar": ["Sugar"],
                                "Sugar syrup": ["Sugar syrup"],
                                "Sunny delight": ["Sunny delight"],
                                "Surge": ["Surge"],
                                "Swedish Punsch": ["Swedish Punsch"],
                                "Sweet and sour": ["Sweet and sour"],
                                "Sweet Vermouth": ["Sweet Vermouth"],
                                "Tabasco sauce": ["Tabasco sauce"],
                                "Tang": ["Tang"],
                                "Tawny port": ["Tawny port"],
                                "Tea": ["Tea"],
                                "Tennessee whiskey": ["Tennessee whiskey"],
                                "Tequila": ["Tequila"],
                                "Tequila Rose": ["Tequila Rose"],
                                "Tia maria": ["Tia maria"],
                                "Tomato juice": ["Tomato juice"],
                                "Tonic": ["Club soda", "Soda water"],
                                "Tonic water": ["Tonic water"],
                                "Triple sec": ["Triple sec"],
                                "Triple Sec": ["Triple Sec"],
                                "Tropicana": ["Tropicana"],
                                "Tuaca": ["Tuaca"],
                                "Vanilla": ["Vanilla"],
                                "Vanilla extract": ["Vanilla extract"],
                                "Vanilla ice-cream": ["Vanilla ice-cream"],
                                "Vanilla liqueur": ["Vanilla liqueur"],
                                "Vanilla schnapps": ["Vanilla schnapps"],
                                "Vanilla syrup": ["Vanilla syrup"],
                                "Vanilla vodka": ["Vanilla vodka"],
                                "Vermouth": ["Vermouth"],
                                "Vodka": ["Vodka"],
                                "Water": ["Water"],
                                "water": ["water"],
                                "Watermelon schnapps": ["Watermelon schnapps"],
                                "Whipped cream": ["Whipped cream"],
                                "Whipping cream": ["Whipping cream"],
                                "Whiskey": ["Whiskey"],
                                "Whisky": ["Whisky"],
                                "White chocolate liqueur": ["White chocolate liqueur"],
                                "White Creme de Menthe": ["White Creme de Menthe"],
                                "White grape juice": ["White grape juice"],
                                "White port": ["White port"],
                                "White rum": ["White rum"],
                                "White wine": ["White wine"],
                                "Wild Turkey": ["Wild Turkey"],
                                "Wildberry schnapps": ["Wildberry schnapps"],
                                "Wine": ["Wine"],
                                "Worcestershire sauce": ["Worcestershire sauce"],
                                "Wormwood": ["Wormwood"],
                                "Yeast": ["Yeast"],
                                "Yellow Chartreuse": ["Yellow Chartreuse"],
                                "Yoghurt": ["Yoghurt"],
                                "Yukon Jack": ["Yukon Jack"],
                                "Zima": ["Zima"]]


}
